const dictionary = [
  { kana: 'あ', alp: ['a'] },
  { kana: 'い', alp: ['i'] },
  { kana: 'う', alp: ['u'] },
  { kana: 'え', alp: ['e'] },
  { kana: 'お', alp: ['o'] },
  { kana: 'か', alp: ['ka', 'ca'] },
  { kana: 'き', alp: ['ki'] },
  { kana: 'く', alp: ['ku', 'cu'] },
  { kana: 'け', alp: ['ke'] },
  { kana: 'こ', alp: ['ko', 'co'] },
  { kana: 'が', alp: ['ga'] },
  { kana: 'ぎ', alp: ['gi'] },
  { kana: 'ぐ', alp: ['gu'] },
  { kana: 'げ', alp: ['ge'] },
  { kana: 'ご', alp: ['go'] },
  { kana: 'さ', alp: ['sa'] },
  { kana: 'し', alp: ['si', 'shi'] },
  { kana: 'す', alp: ['su'] },
  { kana: 'せ', alp: ['se'] },
  { kana: 'そ', alp: ['so'] },
  { kana: 'ざ', alp: ['za'] },
  { kana: 'じ', alp: ['zi', 'ji'] },
  { kana: 'ず', alp: ['zu'] },
  { kana: 'ぜ', alp: ['ze'] },
  { kana: 'ぞ', alp: ['zo'] },
  { kana: 'た', alp: ['ta'] },
  { kana: 'ち', alp: ['ti', 'chi'] },
  { kana: 'つ', alp: ['tu', 'tsu'] },
  { kana: 'て', alp: ['te'] },
  { kana: 'と', alp: ['to'] },
  { kana: 'だ', alp: ['da'] },
  { kana: 'ぢ', alp: ['di'] },
  { kana: 'づ', alp: ['du'] },
  { kana: 'で', alp: ['de'] },
  { kana: 'ど', alp: ['do'] },
  { kana: 'な', alp: ['na'] },
  { kana: 'に', alp: ['ni'] },
  { kana: 'ぬ', alp: ['nu'] },
  { kana: 'ね', alp: ['ne'] },
  { kana: 'の', alp: ['no'] },
  { kana: 'は', alp: ['ha'] },
  { kana: 'ひ', alp: ['hi'] },
  { kana: 'ふ', alp: ['hu', 'fu'] },
  { kana: 'へ', alp: ['he'] },
  { kana: 'ほ', alp: ['ho'] },
  { kana: 'ば', alp: ['ba'] },
  { kana: 'び', alp: ['bi'] },
  { kana: 'ぶ', alp: ['bu'] },
  { kana: 'べ', alp: ['be'] },
  { kana: 'ぼ', alp: ['bo'] },
  { kana: 'ぱ', alp: ['pa'] },
  { kana: 'ぴ', alp: ['pi'] },
  { kana: 'ぷ', alp: ['pu'] },
  { kana: 'ぺ', alp: ['pe'] },
  { kana: 'ぽ', alp: ['po'] },
  { kana: 'ま', alp: ['ma'] },
  { kana: 'み', alp: ['mi'] },
  { kana: 'む', alp: ['mu'] },
  { kana: 'め', alp: ['me'] },
  { kana: 'も', alp: ['mo'] },
  { kana: 'や', alp: ['ya'] },
  { kana: 'ゆ', alp: ['yu'] },
  { kana: 'よ', alp: ['yo'] },
  { kana: 'ら', alp: ['ra'] },
  { kana: 'り', alp: ['ri'] },
  { kana: 'る', alp: ['ru'] },
  { kana: 'れ', alp: ['re'] },
  { kana: 'ろ', alp: ['ro'] },
  { kana: 'わ', alp: ['wa'] },
  { kana: 'を', alp: ['wo'] },
  { kana: 'ん', alp: ['nn', 'xn'] },
  { kana: 'ぁ', alp: ['la', 'xa'] },
  { kana: 'ぃ', alp: ['li', 'xi'] },
  { kana: 'ぅ', alp: ['lu', 'xu'] },
  { kana: 'ぇ', alp: ['le', 'xe'] },
  { kana: 'ぉ', alp: ['lo', 'xo'] },
  { kana: 'うぁ', alp: ['wha'] },
  { kana: 'うぃ', alp: ['wi', 'whi'] },
  { kana: 'うぇ', alp: ['we', 'whe'] },
  { kana: 'うぉ', alp: ['who'] },
  { kana: 'きゃ', alp: ['kya'] },
  { kana: 'きぃ', alp: ['kyi'] },
  { kana: 'きゅ', alp: ['kyu'] },
  { kana: 'きぇ', alp: ['kye'] },
  { kana: 'きょ', alp: ['kyo'] },
  { kana: 'くぉ', alp: ['qo', 'kwo'] },
  { kana: 'ぎゃ', alp: ['gya'] },
  { kana: 'ぎゅ', alp: ['gyu'] },
  { kana: 'ぎょ', alp: ['gyo'] },
  { kana: 'しゃ', alp: ['sya', 'sha'] },
  { kana: 'しゅ', alp: ['syu', 'shu'] },
  { kana: 'しぇ', alp: ['sye', 'she'] },
  { kana: 'しょ', alp: ['syo', 'sho'] },
  { kana: 'じゃ', alp: ['ja', 'jya', 'zya'] },
  { kana: 'じゅ', alp: ['ju', 'jyu', 'zyu'] },
  { kana: 'じぇ', alp: ['je', 'jye', 'zye'] },
  { kana: 'じょ', alp: ['jo', 'jyo', 'zyo'] },
  { kana: 'ちゃ', alp: ['tya', 'cya', 'cha'] },
  { kana: 'ちゅ', alp: ['tyu', 'cyu', 'chu'] },
  { kana: 'ちぇ', alp: ['tye', 'cye', 'che'] },
  { kana: 'ちょ', alp: ['tyo', 'cyo', 'cho'] },
  { kana: 'てぃ', alp: ['thi'] },
  { kana: 'てゅ', alp: ['thu'] },
  { kana: 'とぅ', alp: ['twu'] },
  { kana: 'でぃ', alp: ['dhi'] },
  { kana: 'でゅ', alp: ['dhu'] },
  { kana: 'にゃ', alp: ['nya'] },
  { kana: 'にゅ', alp: ['nyu'] },
  { kana: 'にょ', alp: ['nyo'] },
  { kana: 'ひゃ', alp: ['hya'] },
  { kana: 'ひゅ', alp: ['hyu'] },
  { kana: 'ひょ', alp: ['hyo'] },
  { kana: 'ふぁ', alp: ['fa'] },
  { kana: 'ふぃ', alp: ['fi'] },
  { kana: 'ふぇ', alp: ['fe'] },
  { kana: 'ふぉ', alp: ['fo'] },
  { kana: 'びゃ', alp: ['bya'] },
  { kana: 'びゅ', alp: ['byu'] },
  { kana: 'びょ', alp: ['byo'] },
  { kana: 'ぴゃ', alp: ['pya'] },
  { kana: 'ぴゅ', alp: ['pyu'] },
  { kana: 'ぴょ', alp: ['pyo'] },
  { kana: 'みゃ', alp: ['mya'] },
  { kana: 'みゅ', alp: ['myu'] },
  { kana: 'みょ', alp: ['myo'] },
  { kana: 'ゃ', alp: ['lya', 'xya'] },
  { kana: 'ゅ', alp: ['lyu', 'xyu'] },
  { kana: 'ょ', alp: ['lyo', 'xyo'] },
  { kana: 'りゃ', alp: ['rya'] },
  { kana: 'りゅ', alp: ['ryu'] },
  { kana: 'りょ', alp: ['ryo'] },
  { kana: 'ゔぁ', alp: ['va'] },
  { kana: 'ゔぃ', alp: ['vi'] },
  { kana: 'ゔ', alp: ['vu'] },
  { kana: 'ゔぇ', alp: ['ve'] },
  { kana: 'ゔぉ', alp: ['vo'] },
  { kana: 'っ', alp: ['ltu', 'xtu', 'ltsu', 'xtsu'] },
  { kana: '０', alp: ['0'] },
  { kana: '１', alp: ['1'] },
  { kana: '２', alp: ['2'] },
  { kana: '３', alp: ['3'] },
  { kana: '４', alp: ['4'] },
  { kana: '５', alp: ['5'] },
  { kana: '６', alp: ['6'] },
  { kana: '７', alp: ['7'] },
  { kana: '８', alp: ['8'] },
  { kana: '９', alp: ['9'] },
  { kana: '、', alp: [','] },
  { kana: '。', alp: ['.'] },
  { kana: 'ー', alp: ['-'] },
  { kana: '！', alp: ['!'] },
  { kana: '？', alp: ['?'] },
  { kana: '「', alp: ['['] },
  { kana: '」', alp: [']'] },
  { kana: '（', alp: ['('] },
  { kana: '）', alp: [')'] }
]

const invalidSingleN = [
  'あ',
  'い',
  'う',
  'え',
  'お',
  'な',
  'に',
  'ぬ',
  'ね',
  'の',
  'や',
  'ゆ',
  'よ',
  'にゃ',
  'にゅ',
  'にょ'
]

const genreList = [
  { ja: 'エンジニア', en: 'engineer' },
  { ja: '一般', en: 'general' }
]

const genreListWithAll = [{ ja: '全て', en: 'all' }, ...genreList]

export default (_, inject) => {
  inject('dictionary', dictionary)
  inject('invalidSingleN', invalidSingleN)
  inject('genreList', genreList)
  inject('genreListWithAll', genreListWithAll)
}
